# Excluded sources
excluded:
    - ../Linting
    - ../Pods
    - ../vendor
    - ../Xcode Templates

# Whitelist rules
only_rules:
    - anyobject_protocol
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - comment_spacing
    - compiler_protocol_init
    - computed_accessors_order
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - control_statement
    - convenience_type
    - custom_rules
    - cyclomatic_complexity
    - deployment_target
    - discouraged_direct_init
    - discouraged_object_literal
    - duplicate_enum_cases
    - duplicate_imports
    - empty_collection_literal
    - empty_count
    - empty_enum_arguments
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - fallthrough
    - fatal_error_message
    - file_length
    - file_name_no_space
    - flatmap_over_map_reduce
    - force_cast
    - force_try
    - force_unwrapping
    - function_body_length
    - function_parameter_count
    - generic_type_name
    - identifier_name
    - implicit_getter
    - inert_defer
    - joined_default_parameter
    - large_tuple
    - last_where
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_nsgeometry_functions
    - legacy_random
    - line_length
    - literal_expression_end_indentation
    - mark
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - nesting
    - no_space_in_method_call
    - notification_center_detachment
    - nsobject_prefer_isequal
    - number_separator
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_outlet
    - private_unit_test
    - prohibited_super_call
    - protocol_property_accessors_order
    - reduce_boolean
    - redundant_discardable_let
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_string_enum_value
    - redundant_type_annotation
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - statement_position
    - strong_iboutlet
    - switch_case_alignment
    - syntactic_sugar
    - test_case_accessibility
    - toggle_bool
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - type_body_length
    - type_name
    - unneeded_break_in_switch
    - unneeded_parentheses_in_closure_argument
    - unused_capture_list
    - unused_closure_parameter
    - unused_enumerated
    - unused_import
    - unused_optional_binding
    - valid_ibinspectable
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - void_return
    - xct_specific_matcher
    - yoda_condition
    # - todo # comment todos until all linting errors are fixed

    # Patch 3
    # - implicitly_unwrapped_optional
    # - first_where
    # - reduce_into

# Rules configuration
colon:
    apply_to_dictionaries: false
cyclomatic_complexity:
    ignores_case_statements: true
    warning: 6
function_parameter_count:
    warning: 6
empty_count:
    severity: warning
file_length:
    warning: 600
function_body_length:
    warning: 100
identifier_name:
    min_length: 2
    max_length: 45
line_length:
    warning: 120
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
nesting:
    type_level:
        warning: 5
    function_level:
        warning: 5
shorthand_operator: warning
type_body_length:
    warning: 400
type_name:
    excluded:
        - T
    max_length:
        warning: 50

# Custom rules
custom_rules:
    empty_line_typedef:
        name: "New line after type definition missing"
        regex: "(class|struct|protocol|extension|enum) (?!var)[a-zA-Z0-9:, ]+\\{\n[ \\/]*[a-z@]+"
        message: "Add empty line after type definition"
        severity: error

    empty_line_mark:
        name: "New line after MARK missing"
        regex: "MARK:[^\n]+\n[ \\/]*[a-z@]+"
        message: "Add empty line after `// MARK: -`"
        severity: error

    private_outlets_actions:
        name: "Non-private IBOutlet or IBAction"
        regex: "(@IBAction func|@IBOutlet var)"
        message: "Make IBActions & IBOutlets private"
        severity: error

    no_objcMembers:
        name: "@objcMembers"
        regex: "@objcMembers"
        message: "Explicitly use @objc on each member you want to expose to Objective-C"
        severity: error